-- MySQL Script generated by MySQL Workbench
-- Fri Jun 21 15:57:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema c387folsk9wfjqtp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c387folsk9wfjqtp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c387folsk9wfjqtp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `c387folsk9wfjqtp` ;

-- -----------------------------------------------------
-- Table `c387folsk9wfjqtp`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c387folsk9wfjqtp`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `file` VARCHAR(255) NULL DEFAULT NULL,
  `parentId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_parentId` (`parentId` ASC) VISIBLE,
  INDEX `idx_createdAt` (`createdAt` ASC) VISIBLE,
  CONSTRAINT `Comments_ibfk_1`
    FOREIGN KEY (`parentId`)
    REFERENCES `c387folsk9wfjqtp`.`Comments` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `c387folsk9wfjqtp`.`People`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c387folsk9wfjqtp`.`People` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
